[package]
name = "test_concurrency_idea"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "2.2.0"
percent-encoding = "2.1.0"